<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.24">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>3&nbsp; Estudio de Caso: Calibración de Parámetros y Fallas Eléctricas – Reporte de Investigación - Verano Delfín</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./montecarlo.html" rel="next">
<link href="./fundamentos_teoricos.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dc55a5b9e770e841cd82e46aadbfb9b0.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-b651517ce65839d647a86e2780455cfb.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dc55a5b9e770e841cd82e46aadbfb9b0.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-e0fdce12ac1367d4b47c179a2935dd10.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-2d6d8467bf2e75a99e72accc3c25dba4.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-e0fdce12ac1367d4b47c179a2935dd10.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<script async="" src="https://hypothes.is/embed.js"></script>
<script>
  window.document.addEventListener("DOMContentLoaded", function (_event) {
    document.body.classList.add('hypothesis-enabled');
  });
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Estudio_de_caso.html">Modelo Matemático</a></li><li class="breadcrumb-item"><a href="./Estudio_de_caso.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Estudio de Caso: Calibración de Parámetros y Fallas Eléctricas</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Reporte de Investigación - Verano Delfín</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/Crisperez517/VERANO-DELFIN.git" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="./Reporte-de-Investigación---Verano-Delfín.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Alternar modo oscuro"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefacio</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introducción</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Marco Teórico y Normativa</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./fundamentos_teoricos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Fundamentos Teóricos</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Modelo Matemático</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Estudio_de_caso.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Estudio de Caso: Calibración de Parámetros y Fallas Eléctricas</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Simulación de Equipos (Haier HBC-150)</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./montecarlo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">montecarlo.html</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./conclusiones.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">conclusiones.html</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Referencias</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul>
  <li><a href="#motivación-y-contexto-del-estudio" id="toc-motivación-y-contexto-del-estudio" class="nav-link active" data-scroll-target="#motivación-y-contexto-del-estudio"><span class="header-section-number">3.1</span> Motivación y Contexto del Estudio</a></li>
  <li><a href="#datos-base-cfe-e-indicadores-de-confiabilidad" id="toc-datos-base-cfe-e-indicadores-de-confiabilidad" class="nav-link" data-scroll-target="#datos-base-cfe-e-indicadores-de-confiabilidad"><span class="header-section-number">3.2</span> Datos Base (CFE) e Indicadores de Confiabilidad</a></li>
  <li><a href="#corrección-de-escala-espacial-factor-kappa_espacial" id="toc-corrección-de-escala-espacial-factor-kappa_espacial" class="nav-link" data-scroll-target="#corrección-de-escala-espacial-factor-kappa_espacial"><span class="header-section-number">3.3</span> Corrección de Escala Espacial (Factor <span class="math inline">\(\kappa_{espacial}\)</span>)</a>
  <ul class="collapse">
  <li><a href="#justificación-de-la-reducción-de-escala" id="toc-justificación-de-la-reducción-de-escala" class="nav-link" data-scroll-target="#justificación-de-la-reducción-de-escala"><span class="header-section-number">3.3.1</span> Justificación de la Reducción de Escala</a></li>
  <li><a href="#la-esperanza-matemática-local" id="toc-la-esperanza-matemática-local" class="nav-link" data-scroll-target="#la-esperanza-matemática-local"><span class="header-section-number">3.3.2</span> La Esperanza Matemática Local</a></li>
  </ul></li>
  <li><a href="#distribución-temporal-de-las-fallas" id="toc-distribución-temporal-de-las-fallas" class="nav-link" data-scroll-target="#distribución-temporal-de-las-fallas"><span class="header-section-number">3.4</span> Distribución Temporal de las Fallas</a></li>
  <li><a href="#modelado-del-proceso-de-poisson-no-homogéneo-ppnh" id="toc-modelado-del-proceso-de-poisson-no-homogéneo-ppnh" class="nav-link" data-scroll-target="#modelado-del-proceso-de-poisson-no-homogéneo-ppnh"><span class="header-section-number">3.5</span> Modelado del Proceso de Poisson No Homogéneo (PPNH)</a></li>
  <li><a href="#validación-del-modelo-cálculo-integral" id="toc-validación-del-modelo-cálculo-integral" class="nav-link" data-scroll-target="#validación-del-modelo-cálculo-integral"><span class="header-section-number">3.6</span> Validación del Modelo (Cálculo Integral)</a></li>
  <li><a href="#distribución-log-normal-de-las-duraciones-de-las-fallas" id="toc-distribución-log-normal-de-las-duraciones-de-las-fallas" class="nav-link" data-scroll-target="#distribución-log-normal-de-las-duraciones-de-las-fallas"><span class="header-section-number">3.7</span> Distribución Log-Normal de las Duraciones de las Fallas</a>
  <ul class="collapse">
  <li><a href="#desglose-mensual-de-horas-de-interrupción" id="toc-desglose-mensual-de-horas-de-interrupción" class="nav-link" data-scroll-target="#desglose-mensual-de-horas-de-interrupción"><span class="header-section-number">3.7.1</span> Desglose Mensual de Horas de Interrupción</a></li>
  <li><a href="#cálculo-empírico-de-medias-y-varianzas-por-régimen" id="toc-cálculo-empírico-de-medias-y-varianzas-por-régimen" class="nav-link" data-scroll-target="#cálculo-empírico-de-medias-y-varianzas-por-régimen"><span class="header-section-number">3.7.2</span> Cálculo Empírico de Medias y Varianzas por Régimen</a></li>
  <li><a href="#transformación-analítica-a-parámetros-log-normales" id="toc-transformación-analítica-a-parámetros-log-normales" class="nav-link" data-scroll-target="#transformación-analítica-a-parámetros-log-normales"><span class="header-section-number">3.7.3</span> Transformación Analítica a Parámetros Log-Normales</a></li>
  </ul></li>
  <li><a href="#calibración-de-la-ecuación-diferencial-estocástica-ede" id="toc-calibración-de-la-ecuación-diferencial-estocástica-ede" class="nav-link" data-scroll-target="#calibración-de-la-ecuación-diferencial-estocástica-ede"><span class="header-section-number">3.8</span> Calibración de la Ecuación Diferencial Estocástica (EDE)</a>
  <ul class="collapse">
  <li><a href="#régimen-1-operación-normal-alphat-1" id="toc-régimen-1-operación-normal-alphat-1" class="nav-link" data-scroll-target="#régimen-1-operación-normal-alphat-1"><span class="header-section-number">3.8.1</span> Régimen 1: Operación Normal (<span class="math inline">\(\alpha(t) = 1\)</span>)</a></li>
  <li><a href="#régimen-2-falla-eléctrica-alphat-2" id="toc-régimen-2-falla-eléctrica-alphat-2" class="nav-link" data-scroll-target="#régimen-2-falla-eléctrica-alphat-2"><span class="header-section-number">3.8.2</span> Régimen 2: Falla Eléctrica (<span class="math inline">\(\alpha(t) = 2\)</span>)</a></li>
  <li><a href="#perturbaciones-discretas-apertura-de-puertas-n_puertat" id="toc-perturbaciones-discretas-apertura-de-puertas-n_puertat" class="nav-link" data-scroll-target="#perturbaciones-discretas-apertura-de-puertas-n_puertat"><span class="header-section-number">3.8.3</span> Perturbaciones Discretas: Apertura de Puertas (<span class="math inline">\(N_{puerta}(t)\)</span>)</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Estudio_de_caso.html">Modelo Matemático</a></li><li class="breadcrumb-item"><a href="./Estudio_de_caso.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Estudio de Caso: Calibración de Parámetros y Fallas Eléctricas</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Estudio de Caso: Calibración de Parámetros y Fallas Eléctricas</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="motivación-y-contexto-del-estudio" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="motivación-y-contexto-del-estudio"><span class="header-section-number">3.1</span> Motivación y Contexto del Estudio</h2>
<p>El presente estudio de caso consolida el marco teórico y metodológico de nuestra investigación aplicándolo a un escenario real y altamente crítico: la red de frío para la preservación de vacunas en Tuxtla Gutiérrez, Chiapas. Debido a las altas temperaturas de la región y a la vulnerabilidad de la infraestructura eléctrica ante eventos climáticos, los refrigeradores institucionales de vacunas se enfrentan a una dificultad operativa constante.</p>
<p>Para que nuestra simulacion sea valida, no podemos usar la Ecuación Diferencial Estocástica (EDE) con números aleatorios sin fundamento. En esta sección, calibraremos todos los parámetros de nuestro modelo. Primero, determinaremos la frecuencia de los cortes de energía basándonos en datos oficiales de la Comisión Federal de Electricidad (CFE), modelándolos a través de un Proceso de Poisson No Homogéneo. Posteriormente, utilizaremos la física del enfriamiento para deducir numéricamente los parámetros de la EDE a partir de las especificaciones termodinámicas reales de los refrigeradores.</p>
</section>
<section id="datos-base-cfe-e-indicadores-de-confiabilidad" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="datos-base-cfe-e-indicadores-de-confiabilidad"><span class="header-section-number">3.2</span> Datos Base (CFE) e Indicadores de Confiabilidad</h2>
<p>El objetivo fundamental es modelar la tasa de ocurrencia de interrupciones del suministro eléctrico en el punto específico de Tuxtla Gutiérrez donde se ubicaría el refrigerador de vacunas. Los datos de partida provienen de la Comisión Federal de Electricidad (CFE) <span class="citation" data-cites="cfe2024informe">(<a href="references.html#ref-cfe2024informe" role="doc-biblioref">Comisión Federal de Electricidad 2024</a>)</span>, la cual evalúa la continuidad del suministro a través de dos indicadores internacionales de confiabilidad:</p>
<ol type="1">
<li><p><strong>SAIFI (Índice de la Frecuencia de Interrupción, en número):</strong> El indicador SAIFI mide la frecuencia con que se interrumpe el servicio a los usuarios por causas propias del transportista y se calcula evalúa como: <span class="math display">\[
SAIFI = \frac{\sum \text{Número total de interrupciones por usuario}}{\text{Número total de usuarios}}
\]</span></p></li>
<li><p><strong>SAIDI (Índice de Duración Promedio de Interrupción, en minutos):</strong> El inicador SAIDI mide en minutos el tiempo que los usuarios del servicio de energía eléctrica no cuentan con servicio por causas atribuibles al transportista y se evalúa como: <span class="math display">\[
SAIDI = \frac{\sum \text{Duración total de las interrupciones sufridas por usuario}}{\text{Número total de usuarios}}
\]</span></p></li>
</ol>
<p>Mediante una solicitud de información pública de transparencia dirigida a la CFE, se obtuvo el registro histórico del promedio mensual de interrupciones y su duración para el municipio de Tuxtla Gutiérrez.</p>
<table class="caption-top table">
<caption>Tabla 1. Interrupciones eléctricas en Tuxtla Gutiérrez, Chiapas (Fuente: Solicitud de Transparencia a la CFE).</caption>
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Año</th>
<th style="text-align: center;">Número de interrupciones promedio por mes</th>
<th style="text-align: center;">Duración Promedio de las interrupciones (Horas)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">2019</td>
<td style="text-align: center;">25</td>
<td style="text-align: center;">2.02</td>
</tr>
<tr class="even">
<td style="text-align: center;">2020</td>
<td style="text-align: center;">42</td>
<td style="text-align: center;">1.73</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2021</td>
<td style="text-align: center;">47</td>
<td style="text-align: center;">2.03</td>
</tr>
<tr class="even">
<td style="text-align: center;">2022</td>
<td style="text-align: center;">40</td>
<td style="text-align: center;">2.59</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2023</td>
<td style="text-align: center;">49</td>
<td style="text-align: center;">2.23</td>
</tr>
<tr class="even">
<td style="text-align: center;">2024</td>
<td style="text-align: center;">43</td>
<td style="text-align: center;">2.39</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2025</td>
<td style="text-align: center;">38</td>
<td style="text-align: center;">2.02</td>
</tr>
</tbody>
</table>
<p>Para este modelo, se toma como línea base el comportamiento del año <strong>2024</strong>, el cual indica un promedio de <strong>43 cortes por mes</strong>. Esto resulta en un promedio anual a nivel municipal de:</p>
<p><span class="math display">\[43 \text{ cortes/mes} \times 12 \text{ meses} = 516 \text{ cortes/año}\]</span></p>
</section>
<section id="corrección-de-escala-espacial-factor-kappa_espacial" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="corrección-de-escala-espacial-factor-kappa_espacial"><span class="header-section-number">3.3</span> Corrección de Escala Espacial (Factor <span class="math inline">\(\kappa_{espacial}\)</span>)</h2>
<section id="justificación-de-la-reducción-de-escala" class="level3" data-number="3.3.1">
<h3 data-number="3.3.1" class="anchored" data-anchor-id="justificación-de-la-reducción-de-escala"><span class="header-section-number">3.3.1</span> Justificación de la Reducción de Escala</h3>
<p>El valor de 516 cortes al año es un dato agregado de todo el municipio. En la modelación aplicada, utilizar directamente este valor para un solo refrigerador implicaría asumir que el edificio clínico sufre más de un apagón diario, lo cual no es físicamente real. Este error ocurre al ignorar que un edificio está conectado a un solo nodo de la red, no a todos simultáneamente.</p>
<p>Para solucionar esto, introducimos un factor de escala espacial. De acuerdo con el Programa para el Desarrollo del Sistema Eléctrico Nacional (PRODESEN) y los diagramas de infraestructura del Centro Nacional de Control de Energía (CENACE) <span class="citation" data-cites="sener2024prodesen">(<a href="references.html#ref-sener2024prodesen" role="doc-biblioref">Secretaría de Energía 2024</a>)</span>, la mancha urbana de Tuxtla Gutiérrez está alimentada de manera sectorizada por exactamente <strong>8 subestaciones principales</strong> de distribución (Tuxtla Céntrica, Oriente, Poniente, Terán, Tuxtla Norte, Tuxtla Dos, Mactumatzá y Real del Bosque).</p>
</section>
<section id="la-esperanza-matemática-local" class="level3" data-number="3.3.2">
<h3 data-number="3.3.2" class="anchored" data-anchor-id="la-esperanza-matemática-local"><span class="header-section-number">3.3.2</span> La Esperanza Matemática Local</h3>
<p>Asumiendo que las fallas de transmisión se distribuyen de manera uniforme sobre estas infraestructuras, el riesgo que absorbe el edificio de interés (la subestación Tuxtla Norte, encargada de alimentar la zona de hospitales y laboratorios de la Colonia Maya) corresponde a un octavo del total municipal.</p>
<p><span class="math display">\[\mathbb{E}[N_{local}] = \frac{516 \text{ cortes}}{8 \text{ subestaciones}} = 64.5 \approx 64 \text{ cortes al año}\]</span></p>
<p>Al ajustar al entero más cercano, establecemos una base realista de <strong>64 interrupciones esperadas al año</strong> para nuestra simulación.</p>
</section>
</section>
<section id="distribución-temporal-de-las-fallas" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="distribución-temporal-de-las-fallas"><span class="header-section-number">3.4</span> Distribución Temporal de las Fallas</h2>
<p>Las interrupciones no ocurren de manera homogénea a lo largo del año (es decir, no se presentan exactamente 5.33 cortes idénticos cada mes). La variabilidad mensual depende directamente de los factores climáticos estacionales de la región. Para no asignar los apagones de manera aleatoria, utilizamos el comportamiento documentado en el <em>Informe Anual de la CFE 2024</em> <span class="citation" data-cites="cfe2024informe">(<a href="references.html#ref-cfe2024informe" role="doc-biblioref">Comisión Federal de Electricidad 2024</a>)</span>, específicamente en su página 82, donde se registra la evolución de los indicadores de continuidad del servicio a lo largo de los meses.</p>
<table class="caption-top table">
<caption>Tabla 2. Evolución mensual acumulada de los indicadores SAIDI y SAIFI (Fuente: Informe Anual CFE 2024, p.&nbsp;82).</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Mes</th>
<th style="text-align: center;">SAIDI Acumulado (Horas)</th>
<th style="text-align: center;">SAIFI Acumulado</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Enero</td>
<td style="text-align: center;">0.998</td>
<td style="text-align: center;">0.013</td>
</tr>
<tr class="even">
<td style="text-align: left;">Febrero</td>
<td style="text-align: center;">1.110</td>
<td style="text-align: center;">0.017</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Marzo</td>
<td style="text-align: center;">1.285</td>
<td style="text-align: center;">0.022</td>
</tr>
<tr class="even">
<td style="text-align: left;">Abril</td>
<td style="text-align: center;">2.793</td>
<td style="text-align: center;">0.027</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mayo</td>
<td style="text-align: center;">4.120</td>
<td style="text-align: center;">0.037</td>
</tr>
<tr class="even">
<td style="text-align: left;">Junio</td>
<td style="text-align: center;">5.774</td>
<td style="text-align: center;">0.053</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Julio</td>
<td style="text-align: center;">6.557</td>
<td style="text-align: center;">0.065</td>
</tr>
<tr class="even">
<td style="text-align: left;">Agosto</td>
<td style="text-align: center;">7.905</td>
<td style="text-align: center;">0.080</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Septiembre</td>
<td style="text-align: center;">8.592</td>
<td style="text-align: center;">0.096</td>
</tr>
<tr class="even">
<td style="text-align: left;">Octubre</td>
<td style="text-align: center;">9.063</td>
<td style="text-align: center;">0.103</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Noviembre</td>
<td style="text-align: center;">9.314</td>
<td style="text-align: center;">0.106</td>
</tr>
<tr class="even">
<td style="text-align: left;">Diciembre</td>
<td style="text-align: center;">10.812</td>
<td style="text-align: center;">0.113</td>
</tr>
</tbody>
</table>
<p>Dado que el informe de la CFE publica el indicador SAIFI de forma acumulada, es necesario calcular la diferencia marginal (<span class="math inline">\(\Delta\)</span>) respecto al mes anterior para aislar el peso estadístico de cada mes de forma individual:</p>
<p><span class="math display">\[
\Delta \text{SAIFI}_i = \text{SAIFI}_i - \text{SAIFI}_{i-1}
\]</span></p>
<p>Para distribuir los 64 cortes anuales calculados para la subestación local respetando esta estacionalidad, aplicamos una <strong>regla de tres simple</strong>. Suponiendo que el valor total del SAIFI al final del año (<span class="math inline">\(0.113\)</span>) representa el 100% de las fallas (equivalente a los 64 cortes), entonces el incremento mensual generado en cada periodo (<span class="math inline">\(\Delta \text{SAIFI}_i\)</span>) representara una fracción directamente proporcional de cortes. Expresado de forma general para cualquier mes <span class="math inline">\(i\)</span>, la asignación viene dada por:</p>
<p><span class="math display">\[
\text{Cortes}_i = \left( \frac{\Delta \text{SAIFI}_i}{\text{SAIFI}_{total}} \right) \times \mathbb{E}[N_{local}]
\]</span></p>
<p>Sustituyendo los valores de nuestro escenario (<span class="math inline">\(\text{SAIFI}_{total} = 0.113\)</span> y <span class="math inline">\(\mathbb{E}[N_{local}] = 64\)</span>), la ecuación del modelo es:</p>
<p><span class="math display">\[
\text{Cortes}_i = \left( \frac{\Delta \text{SAIFI}_i}{0.113} \right) \times 64
\]</span></p>
<p>Al hacer este cálculo y redondeando al entero más cercano (realizando un ajuste para mantener la conservación de la suma total en 64), obtenemos la distribución estacional empírica de fallas:</p>
<table class="caption-top table">
<caption>Tabla 3. Distribución estacional de los 64 cortes locales calculada mediante proporcionalidad sobre el SAIFI 2024.</caption>
<colgroup>
<col style="width: 21%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Mes</th>
<th style="text-align: center;"><span class="math inline">\(\Delta\)</span> SAIFI (Mensual)</th>
<th style="text-align: center;">Cortes Exactos Calculados</th>
<th style="text-align: center;">Cortes Asignados (Redondeo)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Enero</td>
<td style="text-align: center;">0.013</td>
<td style="text-align: center;">7.36</td>
<td style="text-align: center;">7</td>
</tr>
<tr class="even">
<td style="text-align: left;">Febrero</td>
<td style="text-align: center;">0.004</td>
<td style="text-align: center;">2.26</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Marzo</td>
<td style="text-align: center;">0.005</td>
<td style="text-align: center;">2.83</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Abril</td>
<td style="text-align: center;">0.005</td>
<td style="text-align: center;">2.83</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mayo</td>
<td style="text-align: center;">0.010</td>
<td style="text-align: center;">5.66</td>
<td style="text-align: center;">6</td>
</tr>
<tr class="even">
<td style="text-align: left;">Junio</td>
<td style="text-align: center;">0.016</td>
<td style="text-align: center;">9.06</td>
<td style="text-align: center;">9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Julio</td>
<td style="text-align: center;">0.012</td>
<td style="text-align: center;">6.79</td>
<td style="text-align: center;">7</td>
</tr>
<tr class="even">
<td style="text-align: left;">Agosto</td>
<td style="text-align: center;">0.015</td>
<td style="text-align: center;">8.49</td>
<td style="text-align: center;">8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Septiembre</td>
<td style="text-align: center;">0.016</td>
<td style="text-align: center;">9.06</td>
<td style="text-align: center;">9</td>
</tr>
<tr class="even">
<td style="text-align: left;">Octubre</td>
<td style="text-align: center;">0.007</td>
<td style="text-align: center;">3.96</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Noviembre</td>
<td style="text-align: center;">0.003</td>
<td style="text-align: center;">1.70</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Diciembre</td>
<td style="text-align: center;">0.007</td>
<td style="text-align: center;">3.96</td>
<td style="text-align: center;">4</td>
</tr>
</tbody>
</table>
<p>El análisis de la Tabla 3 revela con claridad los dos momentos estacionales de mayor vulnerabilidad y frecuencia de cortes en el suministro eléctrico de la región. El pico más severo se registra en <strong>Junio (9 cortes)</strong>, un fenómeno ocasionado por las altas temperaturas extremas registradas en Tuxtla Gutiérrez durante la primavera-verano, las cuales provocaron una saturación en la red de distribución eléctrica debido al uso masivo y simultáneo de sistemas de aire acondicionado. El segundo periodo crítico ocurre durante <strong>Agosto y Septiembre (8 y 9 cortes respectivamente)</strong>, coincidiendo directamente con el máximo histórico de la temporada de lluvias, tormentas tropicales y huracanes en el Sureste mexicano, eventos climáticos que suelen derribar líneas de alta tensión y afectar transformadores locales. En contraste, la época invernal se consolida como el periodo de máxima estabilidad en el servicio.</p>
</section>
<section id="modelado-del-proceso-de-poisson-no-homogéneo-ppnh" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="modelado-del-proceso-de-poisson-no-homogéneo-ppnh"><span class="header-section-number">3.5</span> Modelado del Proceso de Poisson No Homogéneo (PPNH)</h2>
<p>Para integrar estas interrupciones eléctricas dentro de la Ecuación Diferencial Estocástica (EDE) en tiempo continuo <span class="math inline">\(t\)</span>, donde <span class="math inline">\(t \in [0, 365]\)</span> representa los días del año, utilizamos un <strong>Proceso de Poisson No Homogéneo</strong>, cuya intensidad instantánea de eventos <span class="math inline">\(\lambda(t)\)</span> varía en función del tiempo para absorber la estacionalidad climática.</p>
<p>El modelo se construye mediante la suma de una tasa base constante y dos funciones de perturbación gaussianas no normalizadas. La elección de núcleos gaussianos obedece a dos razones analíticas fundamentales:</p>
<ol type="1">
<li><strong>Transición Teórica Suave:</strong> Los fenómenos climáticos (como una ola de calor o la época de huracanes) no inician ni terminan de forma abrupta. Una gaussiana permite modelar la transición gradual de las estaciones sin introducir discontinuidades de salto que volverían inestable la resolución numérica de la EDE.</li>
<li><strong>Correlación Física Estacional:</strong> Permite alinear y concentrar el mayor riesgo de que la EDE salte al estado de falla eléctrica (apagón) exactamente en los días donde el clima ambiental exterior es más adverso.</li>
</ol>
<p>La función analítica propuesta para la intensidad diaria de fallas es:</p>
<p><span class="math display">\[\lambda(t) = \lambda_{base} + A_1 \exp\left(-\frac{(t - \mu_1)^2}{2\sigma_1^2}\right) + A_2 \exp\left(-\frac{(t - \mu_2)^2}{2\sigma_2^2}\right)\]</span></p>
<p>Para calibrar estos coeficientes con los datos empíricos de Tuxtla Gutiérrez (2024), se realiza el siguiente desglose analítico:</p>
<ul>
<li><p><strong>Tasa Base (<span class="math inline">\(\lambda_{base} = 0.0667\)</span>):</strong> Representa el riesgo mínimo de fondo debido a fallas fortuitas o mantenimiento de la red, independiente del clima. Se calcula desde los meses más estables (febrero y noviembre, con 2 cortes al mes). Al dividir este valor, obtenemos la tasa diaria: <span class="math display">\[\lambda_{base} = \frac{2 \text{ cortes}}{30 \text{ días}} \approx 0.0667 \text{ cortes/día}\]</span></p></li>
<li><p><strong>Medias Temporales (<span class="math inline">\(\mu_1 = 152\)</span> y <span class="math inline">\(\mu_2 = 244\)</span>):</strong> Ubican el centro máximo de los picos de riesgo. El primer pico se centra a <strong>principios de junio</strong> (el 1 de junio equivale al día 152 del año), alineándose con el inicio del verano más caluroso. El segundo se centra a <strong>inicios de septiembre</strong> (día 244), el momento históricamente más activo de la temporada de huracanes.</p></li>
<li><p><strong>Amplitudes (<span class="math inline">\(A_1 = 0.2333\)</span> y <span class="math inline">\(A_2 = 0.2333\)</span>):</strong> Capturan la altura máxima de la campana en los días críticos. Como junio y septiembre registraron 9 cortes mensuales, la tasa en su pico es de <span class="math inline">\(9/30 = 0.30\)</span> cortes/día. Dado que la tasa base ya aporta <span class="math inline">\(0.0667\)</span>, la magnitud neta que debe sumar la gaussiana es la diferencia: <span class="math inline">\(0.30 - 0.0667 = 0.2333\)</span>.</p></li>
<li><p><strong>Varianzas Estacionales (<span class="math inline">\(\sigma_1 = 40\)</span> y <span class="math inline">\(\sigma_2 = 30\)</span>):</strong> Controlan el ancho temporal de las afectaciones. Para la ola de calor, se asigna una desviación estándar de <span class="math inline">\(40\)</span> días (varianza <span class="math inline">\(2\sigma_1^2 = 3200\)</span>) para garantizar que la campana sea lo suficientemente ancha como para cubrir desde finales de abril (cuando inician las altas temperaturas) hasta mediados de julio. Para las lluvias, una desviación estándar de <span class="math inline">\(30\)</span> días (varianza <span class="math inline">\(2\sigma_2^2 = 1800\)</span>) modela una perturbación que cubre por completo agosto y septiembre, extendiéndose hacia octubre.</p></li>
</ul>
<p>Sustituyendo cada coeficiente calibrado, la función de intensidad operativa queda definida formalmente como:</p>
<p><span class="math display">\[\lambda(t) = 0.0667 + 0.2333 \exp\left(-\frac{(t - 152)^2}{3200}\right) + 0.2333 \exp\left(-\frac{(t - 244)^2}{1800}\right)\]</span></p>
<div id="fig-lambda-t" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-lambda-t-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="intensidad_lambda.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-lambda-t-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.1: Función de intensidad diaria de fallas eléctricas <span class="math inline">\(\lambda(t)\)</span>. El modelo superpone al ruido constante de fondo dos núcleos gaussianos anchos que abarcan los momentos más críticos del año: la temporada de estiaje y calor extremo (<span class="math inline">\(\mu_1=152\)</span>, <span class="math inline">\(\sigma_1=40\)</span>) y la temporada de tormentas tropicales (<span class="math inline">\(\mu_2=244\)</span>, <span class="math inline">\(\sigma_2=30\)</span>).
</figcaption>
</figure>
</div>
</section>
<section id="validación-del-modelo-cálculo-integral" class="level2" data-number="3.6">
<h2 data-number="3.6" class="anchored" data-anchor-id="validación-del-modelo-cálculo-integral"><span class="header-section-number">3.6</span> Validación del Modelo (Cálculo Integral)</h2>
<p>Por los fundamentos de los Procesos de Poisson No Homogéneos, el número esperado de eventos en cualquier intervalo cerrado <span class="math inline">\((t_1, t_2]\)</span> está determinado por la integral definida de su función de intensidad:</p>
<p><span class="math display">\[\mathbb{E}[N(t_1, t_2)] = \int_{t_1}^{t_2} \lambda(t) dt\]</span></p>
<p>Para validar la consistencia analítica de nuestra función <span class="math inline">\(\lambda(t)\)</span>, particionamos el año de 365 días en 12 subintervalos (correspondientes a los días acumulados de cada mes) y resolvemos numéricamente sus respectivas integrales, contrastando el área teórica bajo la curva contra los objetivos empíricos de la CFE:</p>
<table class="caption-top table">
<caption>Tabla 4. Validación de Valores Esperados por Integral vs.&nbsp;Datos Empíricos de la CFE 2024.</caption>
<colgroup>
<col style="width: 21%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Mes</th>
<th style="text-align: center;">Intervalo de Integración <span class="math inline">\([t_{i-1}, t_i]\)</span></th>
<th style="text-align: center;">Objetivo Empírico (CFE)</th>
<th style="text-align: center;">Esperanza Integral <span class="math inline">\(\mathbb{E}[N]\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Enero</td>
<td style="text-align: center;"><span class="math inline">\([0, 31]\)</span></td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">2.10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Febrero</td>
<td style="text-align: center;"><span class="math inline">\([31, 59]\)</span></td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2.06</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Marzo</td>
<td style="text-align: center;"><span class="math inline">\([59, 90]\)</span></td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">3.26</td>
</tr>
<tr class="even">
<td style="text-align: left;">Abril</td>
<td style="text-align: center;"><span class="math inline">\([90, 120]\)</span></td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">5.56</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mayo</td>
<td style="text-align: center;"><span class="math inline">\([120, 151]\)</span></td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">8.56</td>
</tr>
<tr class="even">
<td style="text-align: left;">Junio</td>
<td style="text-align: center;"><span class="math inline">\([151, 181]\)</span></td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">8.75</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Julio</td>
<td style="text-align: center;"><span class="math inline">\([181, 212]\)</span></td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">8.16</td>
</tr>
<tr class="even">
<td style="text-align: left;">Agosto</td>
<td style="text-align: center;"><span class="math inline">\([212, 243]\)</span></td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">9.40</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Septiembre</td>
<td style="text-align: center;"><span class="math inline">\([243, 273]\)</span></td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">8.29</td>
</tr>
<tr class="even">
<td style="text-align: left;">Octubre</td>
<td style="text-align: center;"><span class="math inline">\([273, 304]\)</span></td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">4.63</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Noviembre</td>
<td style="text-align: center;"><span class="math inline">\([304, 334]\)</span></td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2.38</td>
</tr>
<tr class="even">
<td style="text-align: left;">Diciembre</td>
<td style="text-align: center;"><span class="math inline">\([334, 365]\)</span></td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">2.10</td>
</tr>
</tbody>
</table>
<p>La suma acumulada de las 12 integrales definidas a lo largo de todo el dominio anual arrojó un valor total de <strong>65.25 eventos esperados</strong>. Al comparar este resultado con la meta de 64 cortes empíricos, se observa que el modelo añade, en promedio, una falla anual extra.</p>
<p>Esta desviación hacia arriba es una decisión metodológica deliberada para blindar la simulación de Montecarlo: al ensanchar las campanas de riesgo para cubrir desde abril hasta octubre de manera ininterrumpida, el modelo genera un escenario ligeramente más <strong>conservador y severo</strong> que la simple estadística aislada. Esto garantiza que las proyecciones de estrés térmico sobre la red de frío no subestimen el peligro real al que estarán sometidos los biológicos de la OMS durante las estaciones críticas en Tuxtla Gutiérrez.</p>
</section>
<section id="distribución-log-normal-de-las-duraciones-de-las-fallas" class="level2" data-number="3.7">
<h2 data-number="3.7" class="anchored" data-anchor-id="distribución-log-normal-de-las-duraciones-de-las-fallas"><span class="header-section-number">3.7</span> Distribución Log-Normal de las Duraciones de las Fallas</h2>
<p>Una vez modelada la frecuencia estocástica con la que ocurren las interrupciones eléctricas, el siguiente componente crítico para el simulador termodinámico consiste en determinar cuánto tiempo dura cada apagón (<span class="math inline">\(D\)</span>). La duración de una falla es una variable aleatoria continua estrictamente positiva con una marcada asimetría hacia la derecha (la mayoría de los cortes se resuelven en pocas horas, pero existen eventos atípicos muy prolongados). Por este motivo, la teoría analítica establece que el comportamiento de las duraciones se modela mediante una distribución Log-normal:</p>
<p><span class="math display">\[
D \sim \text{LogNormal}(\mu, \sigma^2)
\]</span></p>
<p>Para calibrar los parámetros de escala <span class="math inline">\(\mu\)</span> (media de los logaritmos) y de forma <span class="math inline">\(\sigma\)</span> (desviación estándar de los logaritmos) para cada régimen estacional, es necesario procesar los indicadores empíricos de la CFE bajo un esquema de desagregación temporal.</p>
<section id="desglose-mensual-de-horas-de-interrupción" class="level3" data-number="3.7.1">
<h3 data-number="3.7.1" class="anchored" data-anchor-id="desglose-mensual-de-horas-de-interrupción"><span class="header-section-number">3.7.1</span> Desglose Mensual de Horas de Interrupción</h3>
<p>De acuerdo con el registro histórico municipal consolidado para el año 2024, la duración promedio general de una interrupción en Tuxtla Gutiérrez fue de <strong><span class="math inline">\(2.39\)</span> horas por corte</strong>. Sabiendo que el factor de escala espacial redujo el riesgo del edificio a una esperanza de <strong><span class="math inline">\(64\)</span> cortes locales al año</strong>, podemos deducir la cantidad total de tiempo que el refrigerador experimentará desabasto eléctrico a lo largo de todo el año:</p>
<p><span class="math display">\[
\text{Horas Totales del Año} = 64 \text{ cortes/año} \times 2.39 \text{ horas/corte} = 152.96 \text{ horas/año}
\]</span></p>
<p>Para distribuir estas <span class="math inline">\(152.96\)</span> horas anuales entre los 12 meses respetando la estacionalidad de la red, utilizamos el indicador SAIDI acumulado del <em>Informe Anual de la CFE 2024</em>. Primero, calculamos la diferencia marginal (<span class="math inline">\(\Delta \text{SAIDI}_i\)</span>) para aislar el impacto de cada mes. Posteriormente, mediante una regla de tres simple, equiparamos el SAIDI total acumulado al final del año (<span class="math inline">\(10.812\)</span> horas) con nuestras <span class="math inline">\(152.96\)</span> horas de afectación local. La asignación de horas de falla para cada mes viene dada por:</p>
<p><span class="math display">\[
\text{Horas del Mes}_i = \left( \frac{\Delta \text{SAIDI}_i}{10.812} \right) \times 152.96
\]</span></p>
<p>Finalmente, para conocer la duración promedio esperada de un corte individual en un mes específico (<span class="math inline">\(E_i\)</span>), se divide el presupuesto de horas asignadas de ese mes entre el número de cortes discretos calculados previamente en la Tabla 3 (<span class="math inline">\(E_i = \text{Horas del Mes}_i / \text{Cortes}_i\)</span>):</p>
<table class="caption-top table">
<caption>Tabla 5. Estimación de la duración promedio mensual por corte a partir de los indicadores SAIDI 2024.</caption>
<colgroup>
<col style="width: 13%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Mes</th>
<th style="text-align: center;">SAIDI Acumulado</th>
<th style="text-align: center;"><span class="math inline">\(\Delta\)</span> SAIDI</th>
<th style="text-align: center;">Horas del Mes Calculadas</th>
<th style="text-align: center;">Cortes del Mes</th>
<th style="text-align: center;">Duración Media <span class="math inline">\(E_i\)</span> (Horas)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Enero</td>
<td style="text-align: center;">0.998</td>
<td style="text-align: center;">0.998</td>
<td style="text-align: center;">14.12</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">2.017</td>
</tr>
<tr class="even">
<td style="text-align: left;">Febrero</td>
<td style="text-align: center;">1.110</td>
<td style="text-align: center;">0.112</td>
<td style="text-align: center;">1.58</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">0.790</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Marzo</td>
<td style="text-align: center;">1.285</td>
<td style="text-align: center;">0.175</td>
<td style="text-align: center;">2.48</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">0.827</td>
</tr>
<tr class="even">
<td style="text-align: left;">Abril</td>
<td style="text-align: center;">2.793</td>
<td style="text-align: center;">1.508</td>
<td style="text-align: center;">21.33</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">7.110</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mayo</td>
<td style="text-align: center;">4.120</td>
<td style="text-align: center;">1.327</td>
<td style="text-align: center;">18.77</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">3.128</td>
</tr>
<tr class="even">
<td style="text-align: left;">Junio</td>
<td style="text-align: center;">5.774</td>
<td style="text-align: center;">1.654</td>
<td style="text-align: center;">23.40</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">2.600</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Julio</td>
<td style="text-align: center;">6.557</td>
<td style="text-align: center;">0.783</td>
<td style="text-align: center;">11.08</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">1.583</td>
</tr>
<tr class="even">
<td style="text-align: left;">Agosto</td>
<td style="text-align: center;">7.905</td>
<td style="text-align: center;">1.348</td>
<td style="text-align: center;">19.07</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">2.384</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Septiembre</td>
<td style="text-align: center;">8.592</td>
<td style="text-align: center;">0.687</td>
<td style="text-align: center;">9.72</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">1.080</td>
</tr>
<tr class="even">
<td style="text-align: left;">Octubre</td>
<td style="text-align: center;">9.063</td>
<td style="text-align: center;">0.471</td>
<td style="text-align: center;">6.66</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">1.665</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Noviembre</td>
<td style="text-align: center;">9.314</td>
<td style="text-align: center;">0.251</td>
<td style="text-align: center;">3.55</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1.775</td>
</tr>
<tr class="even">
<td style="text-align: left;">Diciembre</td>
<td style="text-align: center;">10.812</td>
<td style="text-align: center;">1.498</td>
<td style="text-align: center;">21.19</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">5.298</td>
</tr>
</tbody>
</table>
</section>
<section id="cálculo-empírico-de-medias-y-varianzas-por-régimen" class="level3" data-number="3.7.2">
<h3 data-number="3.7.2" class="anchored" data-anchor-id="cálculo-empírico-de-medias-y-varianzas-por-régimen"><span class="header-section-number">3.7.2</span> Cálculo Empírico de Medias y Varianzas por Régimen</h3>
<p>Para alimentar la conmutación de regímenes de la EDE, agrupamos los meses en las tres temporadas climáticas analizadas. Sin embargo, realizar un promedio aritmético simple entre las duraciones mensuales introduciría un sesgo metodológico, ya que trataría por igual a un mes con 9 cortes que a uno con solo 2 cortes.</p>
<p>Para resolver esto, calculamos la media empírica (<span class="math inline">\(\mathbb{E}[D_{reg}]\)</span>) y la varianza empírica (<span class="math inline">\(\mathbb{V}[D_{reg}]\)</span>) de cada régimen utilizando estadística descriptiva ponderada, donde el peso de cada mes está determinado estrictamente por su número de cortes (<span class="math inline">\(\omega_i = \text{Cortes}_i\)</span>). Analíticamente, las ecuaciones operativas son:</p>
<p><span class="math display">\[
\mathbb{E}[D_{reg}] = \frac{\sum \omega_i E_i}{\sum \omega_i} = \frac{\text{Total de Horas del Régimen}}{\text{Total de Cortes del Régimen}}
\]</span></p>
<p><span class="math display">\[
\mathbb{V}[D_{reg}] = \frac{\sum \omega_i (E_i - \mathbb{E}[D_{reg}])^2}{\sum \omega_i}
\]</span></p>
<p>Agrupando los datos bajo este criterio de ponderación, se obtienen las siguientes métricas muestrales por temporada: * <strong>Régimen de Calor (Mayo, Junio y Julio):</strong> Acumula <span class="math inline">\(22\)</span> cortes y <span class="math inline">\(53.25\)</span> horas de interrupción, resultando en una duración media de <span class="math inline">\(\mathbb{E}[D] = 2.420\)</span> horas y una varianza de <span class="math inline">\(\mathbb{V}[D] = 0.373\)</span>. * <strong>Régimen de Lluvias (Agosto, Septiembre y Octubre):</strong> Suma <span class="math inline">\(21\)</span> cortes y <span class="math inline">\(35.45\)</span> horas de interrupción, generando una duración media de <span class="math inline">\(\mathbb{E}[D] = 1.688\)</span> horas y una varianza de <span class="math inline">\(\mathbb{V}[D] = 0.343\)</span>. * <strong>Régimen Base e Invierno (Resto de meses):</strong> Concentra <span class="math inline">\(23\)</span> cortes y <span class="math inline">\(64.25\)</span> horas, arrojando una duración media de <span class="math inline">\(\mathbb{E}[D] = 2.793\)</span> horas con una varianza más dispersa de <span class="math inline">\(\mathbb{V}[D] = 4.650\)</span> debido a la anomalía de abril.</p>
</section>
<section id="transformación-analítica-a-parámetros-log-normales" class="level3" data-number="3.7.3">
<h3 data-number="3.7.3" class="anchored" data-anchor-id="transformación-analítica-a-parámetros-log-normales"><span class="header-section-number">3.7.3</span> Transformación Analítica a Parámetros Log-Normales</h3>
<p>Una vez que conocemos la media aritmética real (<span class="math inline">\(\mathbb{E}[D]\)</span>) y la varianza geométrica real (<span class="math inline">\(\mathbb{V}[D]\)</span>) del sistema, debemos mapearlas hacia los parámetros analíticos internos <span class="math inline">\(\mu\)</span> y <span class="math inline">\(\sigma\)</span> que requiere la función de distribución de probabilidad en el código de Python.</p>
<p>Por definición matemática, la esperanza matemática y la varianza de una variable aleatoria con distribución Log-normal se rigen por las siguientes dos identidades:</p>
<p><span class="math display">\[
\mathbb{E}[D] = \exp\left(\mu + \frac{\sigma^2}{2}\right)
\]</span></p>
<p><span class="math display">\[
\mathbb{V}[D] = \left[\exp(\sigma^2) - 1\right] \exp(2\mu + \sigma^2) = (\mathbb{E}[D])^2 \left[\exp(\sigma^2) - 1\right]
\]</span></p>
<p>Al resolver este sistema de ecuaciones no lineales de forma algebraica para despejar los parámetros objetivos en función de los momentos estadísticos conocidos, se deducen las fórmulas generales de calibración:</p>
<p><span class="math display">\[
\sigma = \sqrt{\ln\left(1 + \frac{\mathbb{V}[D]}{(\mathbb{E}[D])^2}\right)}
\]</span></p>
<p><span class="math display">\[
\mu = \ln(\mathbb{E}[D]) - \frac{\sigma^2}{2} = \ln\left( \frac{(\mathbb{E}[D])^2}{\sqrt{\mathbb{V}[D] + (\mathbb{E}[D])^2}} \right)
\]</span></p>
<p>Al sustituir las medias y varianzas empíricas ponderadas de cada temporada en estas relaciones analíticas de transformación, obtenemos los parámetros exactos calibrados que gobernará el reloj de simulación de Montecarlo:</p>
<table class="caption-top table">
<caption>Tabla 6. Parámetros lognormales finales calculados mediante el método de momentos ponderados.</caption>
<colgroup>
<col style="width: 13%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Régimen Estacional</th>
<th style="text-align: center;">Meses que lo integran</th>
<th style="text-align: center;">Media Empírica <span class="math inline">\(\mathbb{E}[D]\)</span></th>
<th style="text-align: center;">Varianza Empírica <span class="math inline">\(\mathbb{V}[D]\)</span></th>
<th style="text-align: center;">Parámetro <span class="math inline">\(\mu\)</span></th>
<th style="text-align: center;">Parámetro <span class="math inline">\(\sigma\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Base (Invierno)</strong></td>
<td style="text-align: center;">Ene, Feb, Mar, Abr, Nov, Dic</td>
<td style="text-align: center;">2.793</td>
<td style="text-align: center;">4.650</td>
<td style="text-align: center;">0.7933</td>
<td style="text-align: center;">0.6838</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Calor (Ola de Verano)</strong></td>
<td style="text-align: center;">May, Jun, Jul</td>
<td style="text-align: center;">2.420</td>
<td style="text-align: center;">0.373</td>
<td style="text-align: center;">0.8529</td>
<td style="text-align: center;">0.2485</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Lluvias (Ciclones)</strong></td>
<td style="text-align: center;">Ago, Sep, Oct</td>
<td style="text-align: center;">1.688</td>
<td style="text-align: center;">0.343</td>
<td style="text-align: center;">0.4667</td>
<td style="text-align: center;">0.3371</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="calibración-de-la-ecuación-diferencial-estocástica-ede" class="level2" data-number="3.8">
<h2 data-number="3.8" class="anchored" data-anchor-id="calibración-de-la-ecuación-diferencial-estocástica-ede"><span class="header-section-number">3.8</span> Calibración de la Ecuación Diferencial Estocástica (EDE)</h2>
<p>Enlazando la dinámica de la red eléctrica con la termodinámica, recordamos que la temperatura interna <span class="math inline">\(T(t)\)</span> del refrigerador está gobernada por:</p>
<p><span class="math display">\[dT(t) = \kappa(\alpha(t)) [\theta(\alpha(t)) - T(t)] dt + \sigma(\alpha(t)) dW(t) + \gamma dN_{puerta}(t)\]</span></p>
<p>Para reflejar fielmente a un equipo institucional que cumple el estándar de la OMS (como el modelo Haier HBC-150), calibraremos los coeficientes.</p>
<section id="régimen-1-operación-normal-alphat-1" class="level3" data-number="3.8.1">
<h3 data-number="3.8.1" class="anchored" data-anchor-id="régimen-1-operación-normal-alphat-1"><span class="header-section-number">3.8.1</span> Régimen 1: Operación Normal (<span class="math inline">\(\alpha(t) = 1\)</span>)</h3>
<p>Ocurre cuando hay energía eléctrica y el compresor funciona.</p>
<ul>
<li><p><strong>Temperatura de Consigna (<span class="math inline">\(\theta_1\)</span>)</strong>: Se establece en <strong><span class="math inline">\(5^\circ \text{C}\)</span></strong>, el centro ideal del rango normativo de seguridad (2°C a 8°C).</p></li>
<li><p><strong>Velocidad de Enfriamiento (<span class="math inline">\(\kappa_1\)</span>)</strong>: Representa la capacidad del motor para recuperar la temperatura. Se calibra en <span class="math inline">\(\kappa_1 = 0.1188\)</span>.</p></li>
<li><p><strong>Ruido del Compresor (<span class="math inline">\(\sigma_1\)</span>)</strong>: El motor prende y apaga intermitentemente para mantener los 5°C. Para que el 99.7% del tiempo las fluctuaciones se mantengan en un rango de <span class="math inline">\(\pm 3^\circ \text{C}\)</span> (regla empírica de 3 sigmas del proceso Ornstein-Uhlenbeck), calculamos <span class="math inline">\(\sigma_1 = \sqrt{0.2376} \approx 0.487\)</span>.</p></li>
</ul>
</section>
<section id="régimen-2-falla-eléctrica-alphat-2" class="level3" data-number="3.8.2">
<h3 data-number="3.8.2" class="anchored" data-anchor-id="régimen-2-falla-eléctrica-alphat-2"><span class="header-section-number">3.8.2</span> Régimen 2: Falla Eléctrica (<span class="math inline">\(\alpha(t) = 2\)</span>)</h3>
<p>Se activa cuando el Proceso de Poisson dispara un apagón.</p>
<ul>
<li><p><strong>Temperatura Exterior (<span class="math inline">\(\theta_2\)</span>)</strong>: Para evaluar el caso crítico en Tuxtla Gutiérrez, fijamos una temperatura ambiental extrema de <strong><span class="math inline">\(43^\circ \text{C}\)</span></strong>.</p></li>
<li><p><strong>Inercia Térmica (<span class="math inline">\(\kappa_2\)</span>)</strong>: Los refrigeradores OMS cuentan con paquetes de hielo como “masa térmica”. El equipo Haier garantiza un <em>Holdover Time</em> (tiempo de autonomía) de 63.8 horas a 43°C antes de rebasar los 8°C. Usando la solución analítica de enfriamiento determinista de 5°C a 8°C: <span class="math display">\[8 = 43 + (5 - 43) e^{-\kappa_2 (63.8)}\]</span> Al despejar, obtenemos un valor sumamente bajo de <span class="math inline">\(\kappa_2 \approx 0.00128\)</span>, lo que demuestra la alta efectividad del aislamiento térmico.</p></li>
<li><p><strong>Volatilidad Externa (<span class="math inline">\(\sigma_2\)</span>)</strong>: Sin compresor encendido, las variaciones obedecen solo a micro-filtraciones de aire. Establecemos un ruido menor: <span class="math inline">\(\sigma_2 = 0.05\)</span>.</p></li>
</ul>
</section>
<section id="perturbaciones-discretas-apertura-de-puertas-n_puertat" class="level3" data-number="3.8.3">
<h3 data-number="3.8.3" class="anchored" data-anchor-id="perturbaciones-discretas-apertura-de-puertas-n_puertat"><span class="header-section-number">3.8.3</span> Perturbaciones Discretas: Apertura de Puertas (<span class="math inline">\(N_{puerta}(t)\)</span>)</h3>
<p>Las aperturas de puerta son provocadas activamente por el personal de enfermería para sacar o guardar biológicos.</p>
<ul>
<li><p><strong>Tasa de Aperturas</strong>: Se modelan con un Proceso de Poisson Homogéneo que ocurre solo durante el horario laboral.</p></li>
<li><p><strong>Impacto de la Apertura (<span class="math inline">\(\gamma\)</span>)</strong>: Asignamos un incremento térmico inmediato de <strong><span class="math inline">\(+0.5^\circ \text{C}\)</span></strong> por evento. Esta es la perturbación que altera bruscamente la temperatura.</p></li>
</ul>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-cfe2024informe" class="csl-entry" role="listitem">
Comisión Federal de Electricidad. 2024. <span>«Informe Anual 2024»</span>. Ciudad de México: Gobierno de México.
</div>
<div id="ref-sener2024prodesen" class="csl-entry" role="listitem">
Secretaría de Energía. 2024. <span>«Programa para el Desarrollo del Sistema Eléctrico Nacional (PRODESEN) 2024-2038»</span>. Ciudad de México: Gobierno de México.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./fundamentos_teoricos.html" class="pagination-link" aria-label="Fundamentos Teóricos">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Fundamentos Teóricos</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./montecarlo.html" class="pagination-link" aria-label="montecarlo.html">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">montecarlo.html</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>